### ISSUE TITLE
Improve releasing

### ISSUE THREAD

**Issue by gergelyke** [emartech/suite-js-sdk#2]
It would be great to have the following workflow when adding new features/fixes:

* once a PR gets merged, the corresponding major/minor/patch version number gets updated in the `package.json` by the one who merges the PR
* create a git tag with the version number, and push it: `git tag -a v1.0 -m 'Bumping version to 1.0'`, `git push origin --tags`
* `npm publish`

Also, it would be great to bump the version number to `1.0`, as this is what NPM suggests.

What do you think?

**Comment by drawain** [comment]
Ok, this workflow can work - we will use it after the next PR.
