### ISSUE TITLE
Adding travis?

### ISSUE THREAD

**Issue by gergelyke** [emartech/suite-js-sdk#9]
Would be great to see the build status when creating/merging PRs.

**Comment by gergelyke** [comment]
ping @drawain @Valetudox

**Comment by Valetudox** [comment]
Can you explain a little why travis is better than codeship for this?

**Comment by gergelyke** [comment]
because travis can be public - for example, I cannot see the codeship build for now (I don't know if they have this public-thing feature)

**Comment by Valetudox** [comment]
I will ask codeship about this. I hope we can solve this with them. We dont want to manage +1 ci if not neccessary
